version: '3'

services:
  database:
    image: mysql:5.7
    container_name: database
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Définissez le mot de passe root de MySQL
      MYSQL_DATABASE: coiffure
      MYSQL_USER: hichem
      MYSQL_PASSWORD: hichem  # Définissez le mot de passe pour l'utilisateur MySQL
    ports:
      - 3306:3306
    volumes:
      - dockerAngularSpringDatabaseData:/var/lib/mysql
    networks:
      - backendNetwork

  spring-boot-ems:
    image: openjdk:17-jdk-slim
    container_name: spring-boot-ems
    ports:
      - 8081:8080
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/coiffure?verifyServerCertificate=false&useSSL=false&requireSSL=false&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: hichem
      SPRING_DATASOURCE_PASSWORD: hichem  # Utilisez le même mot de passe que celui défini pour l'utilisateur MySQL
    volumes:
      - ./target/DevCoiff-0.0.1-SNAPSHOT.jar:/DevCoiff-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "DevCoiff-0.0.1-SNAPSHOT.jar"]
    networks:
      - backendNetwork


volumes:
  dockerAngularSpringDatabaseData:

networks:
  backendNetwork:
