version: "3.8"

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=coiffure
      - MYSQL_USER=root
      - MYSQL_PASSWORD=hichem123





    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - 7071:7071
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/coiffure?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "hichem123",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "create"
        }

   







    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
